# GitHub Pages Build Configuration

This file configures Jekyll build for GitHub Pages.
Adding this file can trigger a rebuild of the site.

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge
