#!/bin/bash

# QUICK SETUP COMMANDS FOR LEHOAN
# Copy-paste these commands directly

echo "=========================================="
echo "🚀 RAPTOR [X] - SETUP CHECKLIST"
echo "=========================================="
echo ""

echo "📍 STEP 1: GitHub SSH Key"
echo "==========================================="
echo ""
echo "Your SSH Public Key (copy this):"
echo ""
cat ~/.ssh/id_ed25519.pub
echo ""
echo "👉 Go to: https://github.com/settings/keys"
echo "   - Click 'New SSH key'"
echo "   - Title: 'Render Deploy Key'"
echo "   - Key type: 'Authentication Key'"
echo "   - Paste the key above"
echo "   - Click 'Add SSH key'"
echo ""
echo "✅ DONE: SSH Key"
echo ""

echo "📍 STEP 2: GitHub Pages Setup"
echo "==========================================="
echo ""
echo "👉 Go to: https://github.com/oceantreasurevn-coder/RaptorX/settings/pages"
echo ""
echo "Configure as follows:"
echo "   - Source: 'Deploy from a branch'"
echo "   - Branch: 'main'"
echo "   - Folder: '/ (root)'"
echo "   - Custom domain: 'scaterraptorx.eu'"
echo "   - ✅ Check 'Enforce HTTPS'"
echo "   - Click 'Save'"
echo ""
echo "⏱️  Wait 1-2 minutes..."
echo "✅ DONE: GitHub Pages"
echo ""

echo "📍 STEP 3: Hostinger DNS - A Records"
echo "==========================================="
echo ""
echo "👉 Go to: Hostinger Dashboard > Your Domain > DNS"
echo ""
echo "Add these 4 A Records:"
echo "   Name: @    Type: A    Value: 185.199.108.153"
echo "   Name: @    Type: A    Value: 185.199.109.153"
echo "   Name: @    Type: A    Value: 185.199.110.153"
echo "   Name: @    Type: A    Value: 185.199.111.153"
echo ""
echo "⏱️  Wait 15-30 minutes for DNS to propagate..."
echo ""
echo "Test in terminal:"
echo "   dig scaterraptorx.eu"
echo ""
echo "Should show one of the IPs above"
echo "✅ DONE: Hostinger A Records"
echo ""

echo "📍 STEP 4: Render Web Service"
echo "==========================================="
echo ""
echo "👉 Go to: https://dashboard.render.com/"
echo ""
echo "Create Web Service:"
echo "   - Click 'New +' > 'Web Service'"
echo "   - Connect to GitHub repo: 'RaptorX'"
echo "   - Branch: 'main'"
echo ""
echo "Configure:"
echo "   - Name: 'raptorx-api'"
echo "   - Runtime: Node"
echo "   - Start Command: 'node server.js'"
echo "   - Instance: Free or Starter"
echo ""
echo "Environment Variables (do NOT commit secrets):"
echo "   AI_PROVIDER=openrouter"
echo "   OPENROUTER_API_KEY=YOUR_OPENROUTER_API_KEY_HERE"
echo "   OPENROUTER_MODEL=openrouter/auto"
echo ""
echo "   - Click 'Create Web Service'"
echo ""
echo "⏱️  Wait 2-5 minutes for deployment..."
echo ""
echo "When done, it shows: 'Your service is live at: https://raptorx-api.onrender.com'"
echo ""
echo "🔴 COPY THIS URL!"
echo "✅ DONE: Render Service"
echo ""

echo "📍 STEP 5: Hostinger DNS - API CNAME"
echo "==========================================="
echo ""
echo "👉 Go back to: Hostinger Dashboard > DNS"
echo ""
echo "Add this CNAME Record:"
echo "   Name: api    Type: CNAME    Value: raptorx-api.onrender.com"
echo ""
echo "Note: Replace 'raptorx-api.onrender.com' with your actual Render URL from STEP 4"
echo ""
echo "⏱️  Wait 5-10 minutes..."
echo "✅ DONE: Hostinger CNAME"
echo ""

echo "📍 STEP 6: Test Everything"
echo "==========================================="
echo ""
echo "Run this test script:"
echo "   bash test-deployment.sh"
echo ""
echo "Or test manually:"
echo ""
echo "Test 1 - Website:"
echo "   open https://scaterraptorx.eu"
echo ""
echo "Test 2 - Health Check:"
echo "   curl https://api.scaterraptorx.eu/api/health"
echo ""
echo "Test 3 - Chat API:"
echo "   curl -X POST https://api.scaterraptorx.eu/api/chat \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"messages\":[{\"role\":\"user\",\"content\":\"Hi\"}],\"lang\":\"en\"}'"
echo ""
echo "✅ DONE: Testing"
echo ""

echo "=========================================="
echo "🎉 ALL STEPS COMPLETE!"
echo "=========================================="
echo ""
echo "Your website is now live!"
echo "Website: https://scaterraptorx.eu"
echo "API: https://api.scaterraptorx.eu"
echo ""
